config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :security_keys
  resources :short_mac_is
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/key_derive', to: 'security_keys#new', via: 'get'
  match '/short_maci', to: 'short_mac_is#new', via: 'get'

end

app/models/security_key.rb
class SecurityKey
  include ActiveModel::Model

  attr_accessor :enb_key, :to_pci, :dl_arfcn, :enc_algo, :int_algo
  attr_accessor :new_enb_key, :rrc_enc, :rrc_int, :up_enc

  validate :is_valid?
  # validate :valid_enb_key?
  # validate :valid_pci?
  # validate :valid_dl_arfcn?
  # validates :enc_algo, inclusion: { in: (0..3).map(&:to_s), message: "must one of 0..3" }
  # validates :int_algo, inclusion: { in: (0..3).map(&:to_s), message: "must one of 0..3" }

  def param_encode
    stream = Array.new

    enb_key.delete!(" ")
    enb_key.gsub(/0(x|X)(\d|\w){2}/).to_a.each do |each|
      stream << each.delete("0x").to_i(16)
    end

    stream << to_pci.to_i
    stream << dl_arfcn.to_i
    stream << enc_algo.to_i
    stream << int_algo.to_i

    p stream.join(" ")
  end

  def init?
    enb_key == nil and to_pci == nil and dl_arfcn == nil and enc_algo == nil and int_algo == nil
  end

  private
    def is_valid?
      return true if init?
      valid_enb_key? and valid_pci? and valid_dl_arfcn? and valid_enc_algo? and valid_int_algo?
    end

    def valid_enb_key?
      if enb_key.gsub(/0(x|X)(\d|\w){2}/).to_a.size != 32 or enb_key == ""
        errors.add(:enb_key, "must has 32 hex bytes that start with '0x' or '0X'")
        return false
      end
      return true
    end

    def valid_pci?
      if to_pci.to_i(10) < 0 or to_pci.to_i(10) > 0xFF or to_pci == ""
        errors.add(:to_pci, "must >= 0 and <= 0xFF")
        return false
      end
      return true
    end

    def valid_dl_arfcn?
      if dl_arfcn.to_i(10) < 0 or dl_arfcn.to_i(10) > 0xFFFF or dl_arfcn == ""
        errors.add(:dl_arfcn, "must >= 0 and <= 0xFFFF")
        return false
      end
      return true
    end

    def valid_enc_algo?
      if !(0..3).map(&:to_s).include?(enc_algo) or enc_algo == nil
        errors.add(:enc_algo, "must one of 0..3")
        return false
      end
      return true
    end

  def valid_int_algo?
    if !(0..3).map(&:to_s).include?(int_algo) or enc_algo == nil
      errors.add(:int_algo, "must one of 0..3")
      return false
    end
    return true
  end

end

app/models/short_mac_i.rb
class ShortMacI
  include ActiveModel::Model

  attr_accessor :enb_key, :to_pci, :to_enb_id, :src_pci, :src_enb_id, :int_algo
  attr_accessor :short_mac_i

  validates :int_algo, inclusion: { in: (0..3).map(&:to_s) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/security_keys_controller.rb
class SecurityKeysController < ApplicationController
  def show

  end

  def index

  end

  def new
    @key = SecurityKey.new
  end

  def create
    @key = SecurityKey.new(key_params)
    @key.param_encode

    if @key.valid?
      render 'new'
    else
      render 'new_error'
    end

  end

  private
    def key_params
      params.require(:security_key).permit(:enb_key, :to_pci, :dl_arfcn, :enc_algo, :int_algo)
    end
end

app/controllers/short_mac_is_controller.rb
class ShortMacIsController < ApplicationController
  def show

  end

  def index

  end

  def new
    @maci = ShortMacI.new
  end

  def create
    @maci = ShortMacI.new(maci_params)

    if @maci.valid?
      render 'new'
    else
      render 'new_error'
    end

  end

  private
  def maci_params
    params.require(:short_mac_i).permit(:enb_key, :to_pci, :to_enb_id, :src_pci, :src_enb_id, :int_algo)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = 'SPS-5'

    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/security_keys_help.rb
module SecurityKeysHelp
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">Awesome Tools</a>
    by 10192452
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "SPS-5", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-left">
          <li><%= link_to "SecurityKey", key_derive_path %></li>
          <li><%= link_to "ShortMAC-I", short_maci_path %></li>
          <li><%= link_to "ErrorCode", "#" %></li>
          <li><%= link_to "Ecc", "#" %></li>
        </ul>
        <ul class="nav pull-right">
          <li><%= link_to "BETA 1.0", "#" %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/security_keys/new.html.erb
<% provide(:title, 'Security Key Derive') %>
<h1><%= yield(:title) %></h1>

<%= form_for(@key) do |f| %>

    <div class="form-group">
      <label for="security_key_enb_key">Enb Key / NH:</label>
      <%= f.text_field :enb_key, class:"form-control"%>
      <small id="security_key_enb_key_help" class="form-text text-muted">Only support the hex, separated by a comma</small>
    </div>

    <label for="security_key_to_pci">Target Pci:</label>
    <%= f.text_field :to_pci, class:"form-control"%>

    <label for="security_key_dl_arfcn">DL-ARFCN:</label>
    <%= f.text_field :dl_arfcn, class:"form-control"%>

    <div class="form-group">
      <label for="security_key_enc_algo">Selected Encryption Algorithm:</label>
      <%= f.text_field :enc_algo, class:"form-control"%>
      <small id="security_key_enc_algo_help" class="form-text text-muted">One of the 0..3</small>
    </div>

    <div class="form-group">
      <label for="security_key_int_algo">Selected Integrity Algorithm:</label>
      <%= f.text_field :int_algo, class:"form-control"%>
      <small id="security_key_enc_algo_help" class="form-text text-muted">One of the 0..3</small>
    </div>

    <div class="form-group">
      <button type="submit" class="btn btn-primary btn-lg btn-block">Derive</button>
    </div>

    <% if @key.valid? and !@key.init? %>

        <label for="security_key_new_enb_key">New Enb Key:</label>
        <%= f.text_field :new_enb_key, class:"form-control"%>

        <label for="security_key_rrc_enc">Rrc Encryption Key:</label>
        <%= f.text_field :rrc_enc, class:"form-control"%>

        <label for="security_key_rrc_int">Rrc Integrity Key:</label>
        <%= f.text_field :rrc_int, class:"form-control"%>

        <label for="security_key_up_enc">Up Encryption Key:</label>
        <%= f.text_field :up_enc, class:"form-control"%>
    <% end %>

<% end %>

app/views/security_keys/new_error.html.erb
<% provide(:title, 'Security Key Derive') %>
<h1><%= yield(:title) %></h1>

<%= form_for(@key) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <label for="security_key_enb_key">Enb Key / NH:</label>
      <%= f.text_field :enb_key, class:"form-control"%>
      <small id="security_key_enb_key_help" class="form-text text-muted">Support the hex and decimal, separated by a comma</small>
    </div>

    <label for="security_key_to_pci">Target Pci:</label>
    <%= f.text_field :to_pci, class:"form-control"%>

    <label for="security_key_dl_arfcn">DL-ARFCN:</label>
    <%= f.text_field :dl_arfcn, class:"form-control"%>

    <div class="form-group">
      <label for="security_key_enc_algo">Selected Encryption Algorithm:</label>
      <%= f.text_field :enc_algo, class:"form-control"%>
      <small id="security_key_enc_algo_help" class="form-text text-muted">One of the 0..3</small>
    </div>

    <div class="form-group">
      <label for="security_key_int_algo">Selected Integrity Algorithm:</label>
      <%= f.text_field :int_algo, class:"form-control"%>
      <small id="security_key_enc_algo_help" class="form-text text-muted">One of the 0..3</small>
    </div>

    <button type="submit" class="btn btn-primary btn-lg btn-block">Derive</button>
<% end %>

app/views/security_keys/show.html.erb
<% provide(:title, 'Security Key Derive') %>
<h1><%= yield(:title) %></h1>

app/views/shared/_error_messages.html.erb
<% if object.invalid? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/short_mac_is/new.html.erb
<% provide(:title, 'Short MAC-I Generate') %>
<h1><%= yield(:title) %></h1>

<%= form_for(@maci) do |f| %>

    <div class="form-group">
      <label for="short_mac_i_enb_key">Enb Key / NH:</label>
      <%= f.text_field :enb_key, class:"form-control"%>
      <small id="security_key_enb_key_help" class="form-text text-muted">Support the hex and decimal, separated by a comma</small>
    </div>

    <label for="short_mac_i_to_pci">Target Pci:</label>
    <%= f.text_field :to_pci, class:"form-control"%>

    <label for="short_mac_i_to_enb_id">Target Enb Id:</label>
    <%= f.text_field :to_enb_id, class:"form-control"%>

    <label for="short_mac_i_src_pci">Source Pci:</label>
    <%= f.text_field :src_pci, class:"form-control"%>

    <label for="short_mac_i_src_enb_id">Source Enb Id:</label>
    <%= f.text_field :src_enb_id, class:"form-control"%>

    <div class="form-group">
      <label for="short_mac_i_int_algo">Selected Integrity Algorithm:</label>
      <%= f.text_field :int_algo, class:"form-control"%>
      <small id="short_mac_i_int_algo_help" class="form-text text-muted">One of the 0..3</small>
    </div>

    <div class="form-group">
      <button type="submit" class="btn btn-primary btn-lg btn-block">Generate</button>
    </div>

    <% if @maci.valid? %>

        <label for="short_mac_i_short_mac_i">Shor MAC-I:</label>
        <%= f.text_field :short_mac_i, class:"form-control"%>

    <% end %>

<% end %>

app/views/short_mac_is/new_error.html.erb
<% provide(:title, 'Short MAC-I Generate') %>
<h1><%= yield(:title) %></h1>

<%= form_for(@maci) do |f| %>

    <%= render 'shared/error_messages', object: f.object %>

    <div class="form-group">
      <label for="short_mac_i_enb_key">Enb Key / NH:</label>
      <%= f.text_field :enb_key, class:"form-control"%>
      <small id="security_key_enb_key_help" class="form-text text-muted">Support the hex and decimal, separated by a comma</small>
    </div>

    <label for="short_mac_i_to_pci">Target Pci:</label>
    <%= f.text_field :to_pci, class:"form-control"%>

    <label for="short_mac_i_to_enb_id">Target Enb Id:</label>
    <%= f.text_field :to_enb_id, class:"form-control"%>

    <label for="short_mac_i_src_pci">Source Pci:</label>
    <%= f.text_field :src_pci, class:"form-control"%>

    <label for="short_mac_i_src_enb_id">Source Enb Id:</label>
    <%= f.text_field :src_enb_id, class:"form-control"%>

    <div class="form-group">
      <label for="short_mac_i_int_algo">Selected Integrity Algorithm:</label>
      <%= f.text_field :int_algo, class:"form-control"%>
      <small id="short_mac_i_int_algo_help" class="form-text text-muted">One of the 0..3</small>
    </div>

    <div class="form-group">
      <button type="submit" class="btn btn-primary btn-lg btn-block">Generate</button>
    </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<div class="center hero-unit">
  <h1>Welcome !</h1>
  <h2>This website provide some awesome tools for daily work. Enjoy it !</h2>
</div>

app/views/tools/security_key.html.erb
<% provide(:title, 'Security Key Derive') %>

<h1><%= yield(:title) %></h1>